# Generated by Django 5.2.5 on 2025-09-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='national_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='national_id_images/'),
        ),
    ]
