# Generated by Django 5.2.5 on 2025-11-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_member_of_this_school',
            field=models.BooleanField(default=False),
        ),
    ]
